

public class Generic 
{
    // objects and primitive data convert to string --> toString 

    // toString method that is automatically generated by the Java compiler for every class,or you can write your own custom toString method

    // primitive data types, you can use the String.valueOf

    public static void main(String[] args) {
        
    }
}
